version: "3.7"
services:
    pdns:
        build:
            context: ./pdns
        restart: always
        depends_on:
            - db
    recursor:
        build:
            context: ./recursor
        restart: always
        depends_on: 
            - db
            - pdns
        ports:
            - '53:53'
    db:
        build: 
            context: ./db/
        volumes: 
            - db:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports: 
            - '3306:3306'
    pdns-admin:
        image: ngoduykhanh/powerdns-admin:latest
        ports:
            - '80:80'
        volumes:
            - pdns-admin:/data
        restart: always
        depends_on: 
            - pdns
volumes: 
    db:
        driver: local
    pdns-admin:
        driver: local