version: "3.7"
services:
    pdns:
        build:
            context: ./pdns
        restart: always
        ports:
            - '53:53'
        depends_on:
            - db
    db:
        build: 
            context: ./db/
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: r00t_passw0rd
        ports: 
            - '3306:3306'